###

# @name get_token
POST {{domain_prod}}/auth/realms/square/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {% client.global.set("auth_token", response.body.access_token); %}


###

## @name health_check
#GET {{domain_dev}}/api/health/heartbeat

###

# @name bert_qa
POST {{domain_dev}}/api/question-answering
Content-Type: application/json

{
  "input": [[
    "Who stars in The Matrix?", "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."
  ]],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "adapter_name": "AdapterHub/bert-base-uncased-pf-squad_v2"
}

###