## @name health
#GET {{domain_dev}}/api/main/health/heartbeat
#Authorization: Bearer {{auth_token}}


# @name sentence-transformer
POST {{domain_dev}}/api/main/msmarco-distilbert-base-tas-b/embedding
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.GjHbg5EIF4NYrLw7qPvoYU6lmO5S7ftF_85SZ7O4FJ2lQ5I_pJHdzskW8Dp3AQPpYLzg-yoeNmOBPMOQvOGCZa9Hv_6Rxg1oapCHuSrkDc46vFaSP3-qnvPpbAtGLIASjnSMQMdJTnBedzMjv7DAihsN942q6RBv-zK7BDxmjp1ukX5PRjJTuvfZvafFWvIA_w0BX3HOdHEP_YbqM2qM4uXsjTuRWU0eZshPIz3wsfKxOvmedTxQOCs0aQSU2hwTzxI7oWDSu84666ewHKBjnOrEc4xE36KHza6yqpKafImfKR93P8iUJalUo0tSXd8uEcpUtLqy83oZ6CGc2jSGgFxroSG2iZqrTdlTswo0bM3k-dI2O2_snUx3SabR3BYEZjQ0qBtsaY2paWJEemDbYldgwLmKnUG3Q6C40Oe1AvRZdMs1-FI6eh37i0pvpCauSTDLB_FipRLq0xgiZ-LORXaG9gwXMf2oyY1XifpQwmhq9-yq7_fwBc3qDYnzJ5GjWu6WBfwobMNo7S8q9C4qz_WT7goiLI5XFLouN6TSD9QhqO90a9KDBp1lwu10X353deiDMiw50c_xn6ah5ItDAgcdlhucxaVKPn8390hJnr5qU8wi33G_07pAhU97yqMsqHG8_rB5qSQTBY0eingkIMUBF17qnF71enBp80J-Prc
Content-Type: application/json

{
  "input": [
    "Do aliens exist?"
  ],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "adapter_name": ""
}