services:
  profile-manager:
    image: ukpsquare/profile-manager:latest
    build:
      context: .
      target: build
    command: uvicorn profile_manager.main:app --reload --host 0.0.0.0 --port 10000 --log-config logging.conf
    ports:
    - 10000:10000
    expose:
    - 10000
    env_file:
    - .local.env
    environment:
      API_PREFIX: ""
      WEB_CONCURRENCY: "1"
      KEYCLOAK_BASE_URL: ""
      MODEL_API_URL: ""
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      VERIFY_ISSUER: "0"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SQUARE_PRIVATE_KEY_FILE: /app/private_key.pem
      SQUARE_URL: "http://square"
    depends_on:
    - mongodb
    volumes:
      - ./mongo_files/db:/db
      - ./profile_manager:/app/profile_manager
      - ./private_key.pem:/app/private_key.pem
  mongodb:
    image: mongo:5.0.4
    restart: always
    volumes:
    - ./mongo_files/db:/data/db
    expose:
    - 27017
    env_file:
    - .local.env

# volumes:
#   mongo-data:
