version: '2'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpw
      - POSTGRES_USER=square
      - POSTGRES_DB=square
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./square-backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
      - es
    volumes:
      - migrations-data:/app/migrations

  frontend:
    build: ./square-frontend
    restart: always
    ports:
      - 80:80

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  skill1:
    build: ./reference-skill-example
    restart: always
    ports:
      - 8080:8080
    #environment:
    #  - PORT=5002

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db-data:
    driver: local
  migrations-data:
    driver: local
  es01:
    driver: local