http:
  middlewares:
    prefix-strip:
      stripPrefixRegex:
        regex:
          - "/api/[a-zA-Z0-9_-]+"
    auth:
      basicAuth:
        users:
          - "admin:$apr1$83pydvsn$uhGz52VH057Cd4pTQukD31"

    api-prefix:
      addPrefix:
        prefix: "/api"
