@hostname = localhost:8081
@path_prefix = /api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.Ef6-mZ3bXxR-Zbj89gQ1nho0-j6EE4uicSdMFuLTKjoXMwp64CgGq4ZTVinZonumw06vFbLumSsOIwp8c1v3BgWnbIsL5mqk41t9f26PO8mfuUbXiVb3TvFErE9bFSnnBfK0slRCvvGzFI-zM79mrJqiH3e40P9r0vdtMdATzCnfAt6Fdy60V6prEr4CcLWcZXcn-D24tq-fYEErMoqzwCRWFxATbQ5FMzpi6WwL7xFrYHZj8UGHP3KW8mjykwiaUI9Yb2BzFui3jCXUKKFK8My1sWqDZcrg3hKkViIxaGnLyIgQ-HpoSyLwOokK09Ac_taRJ0g9HY9vK49RhNINkX26E2drrbrrBwTEbk4DsvHPvG_hs7vcjFAmmVo7LWLMfP_m60ecXCk-4-iHIjHpoGt25E4SuKSyXE7FK6xJcrQSZiqTyidaCTDJSIFpVpFx859GfU1dFhlzutv0FE9uvFLbZdhpQqCu5OmRxrD2riWM7pZqyv3b8fems4AoW26ZC-7hTfn5zDnHNYBHxa1O0_cyTn21lbHNgMCXBzqiyZvEpB43otHB_DgZ3ikxxN0nn1-9nKDOVWKLRTNwWBgdStgfiYSlMO7w0TP8hCOVIn3H_RH6jBIdViKW9SpCsMEdlru64URG8dg4Hu9VnC6mTTLlhyjjk4Bb7yh5sUGUXZk
### GET TOKEN
# @name get_token
# @prompt username
# @prompt password
POST /auth/realms/square/protocol/openid-connect/token HTTP/1.1
Host: {{hostname}}
content-type: application/x-www-form-urlencoded

client_id=square-api&grant_type=password&username={{username}}&password={{password}}

### 
# @name get_datasets
GET {{path_prefix}}/dataset HTTP/1.1
Host: {{hostname}}

###
# @name predictor
POST {{path_prefix}}/predict/{{skill_id}}/{{dataset_id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

###
# @name evaluator
POST {{path_prefix}}/evaluate/{{skill_id}}/{{dataset_id}}/{{metric_name}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json
