@hostname = localhost:8000
@path_prefix = api/skill-manager
@token = <ENTER TOKEN>
### GET TOKEN
# @name get_token
# @prompt username
# @prompt password
POST https://{{hostname}}/auth/realms/square/protocol/openid-connect/token HTTP/1.1
Host: {{hostname}}
content-type: application/x-www-form-urlencoded

client_id=square-api&grant_type=password&username={{username}}&password={{password}}


### 
# @name get_skill_manager_heartbeat
GET https://{{hostname}}/{{path_prefix}}/health/heartbeat HTTP/1.1
Host: {{hostname}}

### 
# @name get_skill_types
GET {{path_prefix}}/skill-types HTTP/1.1
Host: {{hostname}}

### 
# @name get_skill_heartbeat
# @prompt skill_url
GET https://{{hostname}}/{{path_prefix}}/health/skill-heartbeat?skill_url={{skill_url}} HTTP/1.1
Host: {{hostname}}
content-type: application/x-www-form-urlencoded

###
# @name get_all_public_skills
GET {{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}

###
# @name get_all_user_skills
# @token =  {{get_token.response.body.access_token}}
GET https://{{hostname}}/{{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name get_skill_by_id
# @prompt id {skill_id}
GET https://{{hostname}}/{{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name get_skill_by_dataset
# @prompt dataset {dataset}
GET {{path_prefix}}/skill/dataset/{{dataset}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name create_skill
POST https://{{hostname}}/{{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "name":"squad_skill",
  "skill_type":"span-extraction",
  "description":"",
  "skill_settings": {
    "requires_context": false,
    "requires_multiple_choices":0
  },
  "url":"http://open-extractive-qa",
  "default_skill_args": {
  },
  "user_id":"LOCAL_SQUARE_USER",
  "published":true,
  "data_sets": ["squad"],
  "skill_input_examples": [
    {"query":"","context":""},
    {"query":"","context":""},
    {"query":"","context":""}
  ]
  }

###
# @name update_skill_by_id
# @prompt id {skill_id}
PUT https://{{hostname}}/{{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
    ""
}

###
# @name delete_skill_by_id
# @prompt id {skill_id}
DELETE https://{{hostname}}/{{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}


###
# @name publish_skill_by_id
# @prompt id {skill_id}
POST https://{{hostname}}/{{path_prefix}}/skill/{{id}}/publish HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name unpublish_skill_by_id
# @prompt id {skill_id}
POST https://{{hostname}}/{{path_prefix}}/skill/{{id}}/unpublish HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name query_skill_by_id
# @prompt id {skill_id}
POST https://{{hostname}}/{{path_prefix}}/skill/{{id}}/query HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "query": "Which NFL team represented the AFC at Super Bowl 50?",
  "skill_args": {"context": "Super Bowl 50 was an American football game to determine the champion of the National Football League (NFL) for the 2015 season. The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl title."},
  "skill": {},
  "user_id": "",
  "explain_kwargs": {}
}


