@hostname = localhost:8000
@path_prefix = /api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.WiGgv4elnaL32bvdMuCDqL863V454qFYK-9mIkuk3--kurRjI2KjEkMPogEMY9Vv8GD_MxuENYVk50Iibz3lQ1DYlAk0xD0nV2ioOv2weudE53gq-cE109r7FKNNYgT34xkAWLp_jGYqUJUQFld65QhVsD-VIanVTdN4_Wdo3fSGpOF_4JqbligDwqRrNZceSPxfOod3EpNNEM3kDidT2W283wSnv3uNCQkooSquFrWKDi8zAy5DOW0c_xlWYCEdDlco9shCr0i0JxGvA2W1JyKEIpzIORTG-anHd-rZAN67c-Ez8KAVSXhUwgPh7K1cDx-zxQdOeuY2mUso8abVlIl_j5xkC2WzZs_234yrUVEHOKflRqhLlbXqUt8tIrlrhKcVg4L49qduraXEE2tmCfax3hwCcmgYL4IPUz3qZc5fIZL2SjLQSagXVuCB5ux0EsOMTjVW5fjvYAeXvP7s-wXMVcOwJOy6SDjiDGJovuvADYWUDvNfmjlc3iJ2fTAi5eAlGwKHnpuXowSvGnfhgC7qjoelKiEUOegOezBfXZBV6YSl3-AIZf9_ypw7zLZYuGpl4IShOo6wAonYVkO-d6Xm5-Uxj3vNNqMvTrbmJ1AWxRnaXXr46DRrkarU4EPZtSI3tJGUsEI93EAzh80HTQnLDOyKjsi6DG8OQeFOizk
### GET TOKEN
# @name get_token
# @prompt username
# @prompt password
POST /auth/realms/square/protocol/openid-connect/token HTTP/1.1
Host: {{hostname}}
content-type: application/x-www-form-urlencoded

client_id=square-api&grant_type=password&username={{username}}&password={{password}}


### 
# @name get_skill_manager_heartbeat
GET {{path_prefix}}/health/heartbeat HTTP/1.1
Host: {{hostname}}

### 
# @name get_skill_types
GET {{path_prefix}}/skill-types HTTP/1.1
Host: {{hostname}}

### 
# @name get_skill_heartbeat
# @prompt skill_url
GET {{path_prefix}}/health/skill-heartbeat?skill_url={{skill_url}} HTTP/1.1
Host: {{hostname}}
content-type: application/x-www-form-urlencoded

###
# @name get_all_public_skills
GET {{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}

###
# @name get_all_user_skills
# @token =  {{get_token.response.body.access_token}}
GET {{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name get_skill_by_id
# @prompt id {skill_id}
GET {{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name create_skill
POST {{path_prefix}}/skill HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "name":"test-skill",
  "skill_type":"span-extraction",
  "description":"",
  "skill_settings": {
    "requires_context": false,
    "requires_multiple_choices":0
  },
  "url":"http://open-extractive-qa",
  "default_skill_args": {
  },
  "user_id":"LOCAL_SQUARE_USER",
  "published":false,
  "skill_input_examples": [
    {"query":"","context":""},
    {"query":"","context":""},
    {"query":"","context":""}
  ]
  }

###
# @name update_skill_by_id
# @prompt id {skill_id}
PUT {{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
    ""
}

###
# @name delete_skill_by_id
# @prompt id {skill_id}
DELETE {{path_prefix}}/skill/{{id}} HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}


###
# @name publish_skill_by_id
# @prompt id {skill_id}
POST {{path_prefix}}/skill/{{id}}/publish HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name unpublish_skill_by_id
# @prompt id {skill_id}
POST {{path_prefix}}/skill/{{id}}/unpublish HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}

###
# @name query_skill_by_id
# @prompt id {skill_id}
POST {{path_prefix}}/skill/{{id}}/query HTTP/1.1
Host: {{hostname}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "query": "When was the UN founded?",
  "skill_args": {},
  "skill": {},
  "user_id": "",
  "explain_kwargs": {}
}

