FROM python:3.7.6-slim-buster as base

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update
RUN apt-get -y install git

WORKDIR /app

RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY main.py main.py
COPY ./%%SKILL%%/skill.py skill.py 
COPY logging.conf logging.conf

EXPOSE %%PORT%%

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "%%PORT%%", "--log-config", "logging.conf"]
