from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, validator

from evaluator.mongo.mongo_model import MongoModel
from evaluator.mongo.py_object_id import PyObjectId


class Example(MongoModel):
    id: Optional[PyObjectId] = Field(
        None, description="Identifier generated by mongoDB"
    )
    name: str = Field(..., description="Test name.")
    something: str = Field(..., description="Something. Something.")

    class Config:
        schema_extra = {
            "example": {
                "name": "My Example",
                "something": "Something something.",
            }
        }
