# only for dev work

version: "3.3"

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.9.14-management
    ports:
      - 5672:5672
      - 15672:15672
    #    env_file:
    #      - ./management_server/.env
    env_file:
      - .env
    #    volumes:
    #      - ./management_server/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #      - ./management_server/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - '6379:6379'
    #    env_file:
    #      - .env
    env_file:
      - .env
    command: [ "redis-server", "--requirepass ${REDIS_PASSWORD}" ]

  mongo:
    hostname: mongo
    image: mongo:5.0.4
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env

  maintaining_worker:
#    image: ukpsquare/square-model-management-v2:latest
#    build: ./management_server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maintaining_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
#    env_file:
#      - ./management_server/.env
    env_file:
      - .env
    environment:
      - DOCKER_HOST_URL=https://172.17.0.1:8443
      - MODEL_API_IMAGE=ukpsquare/model-inference
      - MONGO_INITDB_ROOT_USERNAME=root
      - VERIFY_SSL=0
      - KEYCLOAK_BASE_URL=https://square.ukp-lab.de
      - REALM=square
      - CLIENT_ID=models
    links:
      - rabbit
      - redis
    depends_on:
      - maintaining
      - rabbit
      - redis

  maintaining:
#    image: ukpsquare/square-model-management-v2:latest
    command: uvicorn model_manager.main:app --host 0.0.0.0 --port 9001 --log-config logging.conf
    container_name: maintaining
#    build: ./management_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo
    depends_on:
      - mongo
#    env_file:
#      - ./management_server/.env
    env_file:
      -  .env
    environment:
      - DOCKER_HOST_URL=https://172.17.0.1:8443
      - MODEL_API_IMAGE=ukpsquare/model-inference
      - VERIFY_SSL=0
      - WEB_CONCURRENCY=1
      - ONNX_VOLUME=model-inference_onnx-models
      - KEYCLOAK_BASE_URL=https://square.ukp-lab.de
      - REALM=square
      - CLIENT_ID=models
      - CONFIG_PATH=/model_configs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintaining.rule=PathPrefix(`/api/models`)"
      - "traefik.http.routers.maintaining.entrypoints=websecure"
      - "traefik.http.routers.maintaining.tls=true"
      - "traefik.http.routers.maintaining.tls.certresolver=le"
      - "traefik.http.routers.maintaining.middlewares=maintaining-stripprefix,maintaining-addprefix"
      - "traefik.http.middlewares.maintaining-stripprefix.stripPrefixRegex.regex=/api/[a-zA-Z0-9_-]+"
      - "traefik.http.middlewares.maintaining-addprefix.addPrefix.prefix=/api"

volumes:

  mongo-data:
    driver: local