###

# @name get_token
POST {{domain_prod}}/auth/realms/square/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}

> {% client.global.set("auth_token", response.body.access_token); %}


###

# @name health_check
GET {{domain_dev}}/api/health/heartbeat

###
